---
- name: "Ansible | List all known variables and facts"
  hosts: all
  tasks:
    - name: "debug groups"
      debug:
        var: groups
    - name: "debug group names"
      debug:
        var: group_names
    - name: "Inventory Hosts"
      debug:
        var: ansible_play_hosts
