---
- name: "Ansible | List all known variables and facts"
  hosts: all
  tasks:
    - name: "debug groups"
      debug:
        var: groups
    - name: "debug group names"
      debug:
        var: group_names
    - name: "Inventory Hosts"
      debug:
        var: ansible_play_hosts
    - name: "Included Group Files"
      debug:
        var: mygroupname
    - name: "Ansible_fqdn"
      debug:
        var: ansible_fqdn
    - name: "Morpheus? fqdn"
      debug:
        var: fqdn
    - name: "Morpheus Hostname"
      debug:
        var: hostname
