---
- name: Morpheus Vars
  hosts: all
 
  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ morpheus | to_nice_json }} 
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
