---
  - name: Shell Test Example
    hosts: all
    tasks:
    
    - name: List Ansible Working folder
      become: yes
      become_user: {{ ansible_user }}
      ansible.builtin.command: "echo $HOME"
      args:
        chdir: ~
        
      register: fileout
      tags: fileout
      
    - debug: msg="{{ fileout.stdout }}"
